server:
  port: 20030
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20020/eureka/
  instance:
    prefer-ip-address: false
spring:
  application:
    name: consumer-movie
feign:
  hystrix:
    enabled: true
